### ISSUE TITLE
Python 3.5 compatibility

### ISSUE THREAD

**Issue by mick88** [lukin0110/poeditor-client#11]
Python 3.5 is currently pre-installed with Ubuntu 16.04 LTS which is still supported. It would make sense to support it as it's widely used. Is there anything preventing the project to run under Python 3.5?

**Comment by mick88** [comment]
Added MR. Not sure if it's fully working, but fixes pushTerms command for me

**Comment by OmarIthawi** [comment]
Fixed in #12. Thanks @mick88!
